// Code generated by MockGen. DO NOT EDIT.
// Source: tools/crxpto.go

// Package tools is a generated GoMock package.
package tools

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockHashInterface is a mock of HashInterface interface.
type MockHashInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHashInterfaceMockRecorder
}

// MockHashInterfaceMockRecorder is the mock recorder for MockHashInterface.
type MockHashInterfaceMockRecorder struct {
	mock *MockHashInterface
}

// NewMockHashInterface creates a new mock instance.
func NewMockHashInterface(ctrl *gomock.Controller) *MockHashInterface {
	mock := &MockHashInterface{ctrl: ctrl}
	mock.recorder = &MockHashInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashInterface) EXPECT() *MockHashInterfaceMockRecorder {
	return m.recorder
}

// ComparePassword mocks base method.
func (m *MockHashInterface) ComparePassword(hashedPassword []byte, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePassword", hashedPassword, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// ComparePassword indicates an expected call of ComparePassword.
func (mr *MockHashInterfaceMockRecorder) ComparePassword(hashedPassword, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePassword", reflect.TypeOf((*MockHashInterface)(nil).ComparePassword), hashedPassword, password)
}

// HashPassword mocks base method.
func (m *MockHashInterface) HashPassword(password string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockHashInterfaceMockRecorder) HashPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockHashInterface)(nil).HashPassword), password)
}
